### ISSUE TITLE
Unify naming of the package

### ISSUE THREAD

**Issue by glensc** [Taxel/PlexTraktSync#540]
### Feature description

There are many forms this application and its script are referred:
- PlexTraktSync: project, project directory
- Plex-Trakt-Sync: in README
- PlexTraktSync: PyPI index, but accepts `plextraktsync`
- plextraktsync: docker image: `ghcr.io/taxel/plextraktsync` (must be lowercase)
- plex_trakt_sync: script added to PATH by pip/pipx
- plex-trakt-sync: container name in docker-compose
- plex_trakt_sync: Python module name (`python3 -m plex_trakt_sync`)
- plex_trakt_sync.sh wrapper script
- plex_trakt_sync.bat wrapper script
- $CACHE_DIR/PlexTraktSync (path in system mode)
- $CONFIG_DIR/PlexTraktSync (path in system mode)
- $LOGS_DIR/PlexTraktSync (path in system mode)

### Use case

This is confusing for user, and developers, which form to use and where, also documentation gets more and more fuzzier.

### Extra

1. `pipx` defaults to project name, so this won't work:
    ```
    pipx run PlexTraktSync
    ```
    need to override with [spec](https://github.com/pypa/pipx#walkthrough-running-an-application-in-a-temporary-virtual-environment):
    ```
    pipx run --spec PlexTraktSync plex_trakt_sync
    ```
2. docker image must be lowercase: `plextraktsync`
3. you can't use `-` as symbols in python code, as that would be typically subtraction operation instead

### Proposition 2

Use `plextraktsync` everywhere:

- [x] change container name in docker-compose.yml: [#553](https://github.com/Taxel/PlexTraktSync/pull/553)
- [x] rename entrypoint for pypi package: [#554](https://github.com/Taxel/PlexTraktSync/pull/554)
- [x] rename wrapper scripts: [#555](https://github.com/Taxel/PlexTraktSync/pull/555)

next would be the change python module may even be omitted, as not directly related to end-user interaction, but for unifying, should still do it (eventually).
- [ ] rename python module

and if wanting to match case as well:
- [ ] use plextraktsync in config/cache/log dirs (system mode)
- [ ] rename pypi.org/project/plextraktsync package
- [ ] rename repo Taxel/PlexTraktSync

same here, using the wrong case does not break things, just inconsistent.

cc @Taxel @twolaw

**Comment by glensc** [comment]
@Taxel so, how about you, we go with `plextraktsync` then?

**Comment by glensc** [comment]
but if the goal is unifying, using `plextraktsync` will then lead to extra changes:
- change python module
- rename wrapper scripts

still, go with that?

**Comment by glensc** [comment]
so, let's go with `plextraktsync` plan?
- https://github.com/Taxel/PlexTraktSync/issues/540#issuecomment-941971583

all agree? @twolaw @Taxel?

**Comment by glensc** [comment]
Ok, this is fine enough. case differences remain, but they don't matter
